services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9126:9126"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm start